### PR TITLE
roxygenized doc for s3HTTP, resolves Codoc mismatches from documentat…

### PR DESCRIPTION
**Pull request by almartin82**
started to run CMD check per #1 - warnings around mismatched documentation.  moved to roxygen2-style documentation, per [hadley](http://r-pkgs.had.co.nz/man.html).  There's also a little bit of linting moving courtesy the [lintr] defaults. (https://github.com/jimhester/lintr).

@leeper are you OK with roxygen2 docs?  I don't think we can submit to CRAN unless we clear those warnings, and roxygen2 has some easy tools for inheritance/documenting multiple functions at once.

### CODE REVIEW

**Comment by cboettig** [comment]
:+1: LGTM

**Comment by leeper** [comment]
This looks like it dropped imports from httr and AWS.signature?

Totally fine with roxygen.

**Comment by almartin82** [comment]
going to call this a night -- this branch is still screwed up, but there are at least some breadcrumbs here  for what the encrypted travis variables are for testing

**Comment by leeper** [comment]
Pull the latest version from master. The issue was most of the functions had references to a non-existent `header` object. I've removed these.

**Comment by almartin82** [comment]
tests passing :+1: :+1: 

I think I found it - it was [this](https://github.com/cloudyr/aws.s3/commit/520571466e7652d73124cf75088d4a40f45b3ab6#diff-062ee42d9e0bdfde64be0f4b3b40d7acR58) call to response in `http.r` which I think was just an unintentional duplicate. 

I reworked the flow in `parse_response` -- would love a code review and any thoughts!

**Comment by leeper** [comment]
:+1:

**Pull request merged**
