### PR TITLE
Remove superfluous call to get_region

### LINKED ISSUE #189: Unable to use a custom base_url with delete_object
I was writing a function delete an Object from a DigitalOcean Space (which follows the AWS S3 API) using `aws.s3::delete_object` and was getting an error about a bucket not found. A quick debug and a look at the source of `delete_object` revealed the cause was a superfluous call to 

https://github.com/cloudyr/aws.s3/blob/c28925d8237979273c3bc57df67629b979891a06/R/delete_object.R#L21

It's superfluous in that it isn't used later on in the function body and, because I'm querying a custom endpoint and the function (appears?) hard-coded to only support AWS, I was getting an error.

Since this line of code isn't doing anything, I'm going to submit a PR so, if you agree with my change, this can get closed out quickly.

### PR DESCRIPTION
**Pull request by amoeba**
Resolves #189 

This was breaking my use case of using a custom base_url which
is how I found it in the first place.

### CODE REVIEW

**Comment by leeper** [comment]
I think this is now unnecessary in light of: https://github.com/cloudyr/aws.s3/commit/eade43c4abc6662bf4f0eee1d1af92da0323767c

**Comment by amoeba** [comment]
Thanks for taking a look, @leeper. I think the call is still superfluous. That, or I'm not aware of why it's being called at all so you may still want to merge this just to tidy up the function body.

**Comment by leeper** [comment]
I'm going to take another look at this as it was added to solve a different problem, which I fear may re-occur. I'll update here if anything relevant changes.

**Comment by amoeba** [comment]
Right on, thanks. I think my issue is solved by that PR, as you indicate, so no worries either way.

**Pull request closed without merging**
