### PR TITLE
Minio support

### PR DESCRIPTION
**Pull request by kaneplusplus**
This pull request adds [minio ](https://minio.io/) to aws.s3. The following changes were made:

1. The host is now included in the header. It looks like the host was *not* included in the header despite the fact that the has was included when generating the signature. Presumably, the s3 server detects that it is not present and fills in s3.amazon.com.
2. The `base_url` is now stored in the aws.s3 namespace. It can be set and retrieved with `set_base_url` and `set_base_url` respectively. This makes it easier to use with non-standard servers.
3. Testing was added for minio. The public server (https://play.minio.io:9000) is used to test the functionality.

### CODE REVIEW

**Comment by leeper** [comment]
I'm sympathetic to this PR, but I don't like the implementation. Rather than using a custom function (https://github.com/cloudyr/aws.s3/pull/194/files#diff-f624098ec4d23f8cbc0468fcaef383feR21), let's use an environment variable `AWS_S3_URL`, which can be called using `Sys.getenv("AWS_S3_URL")` here:

- https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L43
- https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L219

**Comment by kaneplusplus** [comment]
Storing as an environment variable, rather than package variable, means it needs to be set - even when the user wants to connect to `s3.amazon.com`. I'm happy to revise the pull request, but are you sure you want to do this? The current behavior of the package will change.

**Comment by kaneplusplus** [comment]
As a follow up, item 2 in my list was relatively minor. It made it a lot easier to keep the package pointed to the correct service. Item 1 is much less minor.

**Comment by leeper** [comment]
Thanks again. The environment variable route is the right way to go. I've implemented in a backwards compatible manner.

**Comment by kaneplusplus** [comment]
No problem. I'm happy to help. I think the package is great.

**Pull request closed without merging**
