### PR TITLE
add s3saveRDS and s3readRDS functions

### PR DESCRIPTION
**Pull request by skasingularity**
I've added a couple of functions to replicate the functionality of loadRDS and saveRDS for s3. I basically modified the s3load and s3save functions to be more targeted to loading/saving single objects.

Inspiration comes from [this](http://www.fromthebottomoftheheap.net/2012/04/01/saving-and-loading-r-objects/) article.

### CODE REVIEW

**Comment by leeper** [comment]
Thanks for this. Would you like authorship credit? If so, feel free to add your details in DESCRIPTION and the roxygen markup for these functions.

**Comment by skasingularity** [comment]
I added the author tags, thanks!

**Comment by leeper** [comment]
Thanks. I'll merge this in, hopefully later today.

**Comment by skasingularity** [comment]
I've made a couple of changes to these functions, namely:

- changing the "opts" argument to just be ..., simplifying the function
- updating them to use serialize/deserialize in order to address: [issue 51](https://github.com/cloudyr/aws.s3/issues/51)

**Pull request merged**
