### PR TITLE
Memory optimized multipart upload

### PR DESCRIPTION
**Pull request by an2deg**
Please find fixed and refactored put_object() function.
Refactoring was performed to make  put_object() more memory effective: previous implementation used 2x<file size> memory which was very problematic for using it with huge files. New version keeps in memory only a single chunk of a file (100Mb).
Code was tested with minio (custom S3 endpoint) and with real AWS S3 for files 20Mb and 200Mb

### CODE REVIEW

**Comment by an2deg** [comment]
I'm working on resolving conflicts right now

**Comment by an2deg** [comment]
I have picked up all the changes from upstream, merged them and re-tested. Please take a look into my pull request

**Comment by leeper** [comment]
Okay, I really like the spirit of this PR but I also think there are a lot of changes going on here many of which are not necessary or strictly related to the core functionality improvement. There are also some unrelated fixes (e.g., region handling in `delete_object()`) that might be good but need to be a separate PR.

What I'd like to see here is a PR that just does the following:

- Modify [the current `readBin()` call](https://github.com/cloudyr/aws.s3/blob/master/R/put_object.R#L91-L93) and replace it with your [reading from a connection code](https://github.com/cloudyr/aws.s3/pull/242/files#diff-2d8b77e6d1bc20f44c00feab8cd3cdfdR239)
- Replace the current raw vector subsetting here: https://github.com/cloudyr/aws.s3/blob/master/R/put_object.R#L133 and here: https://github.com/cloudyr/aws.s3/blob/master/R/put_object.R#L137 with your [reading from connection code](https://github.com/cloudyr/aws.s3/pull/242/files#diff-2d8b77e6d1bc20f44c00feab8cd3cdfdR280)

I can do these modifications in the spirit of your PR or you can update. Let me know which you'd prefer.

**Comment by an2deg** [comment]
Hi Thomas,

Thank you for feedback. Ok, let's me do all the changes from my side to being sure that it will work in all my cases

**Comment by an2deg** [comment]
btw, current implementation of calculating Content-Length has a problem: in case of empty strings ("") it returns 1 instead of 0.
That's why I implemented calculate_data_size() function. If you wouldn't mind I will use it as well in a refactored pull request

**Comment by leeper** [comment]
That's totally fine!

**Comment by leeper** [comment]
This looks good on glance. Can you also add yourself as a contributor to the DESCRIPTION file?

**Comment by an2deg** [comment]
Here you are, Thomas!

**Comment by leeper** [comment]
Thanks very much!

**Pull request merged**
