### PR TITLE
Use hostname:port from AWS_S3_ENDPOINT as host for signature calculation

### PR DESCRIPTION
**Pull request by rvolykh**
Please ensure the following before submitting a PR:

 - [x] if suggesting code changes or improvements, [open an issue](https://github.com/cloudyr/aws.s3/issues/new) first
 - [ ] for all but trivial changes (e.g., typo fixes), add your name to [DESCRIPTION](https://github.com/cloudyr/aws.s3/blob/master/DESCRIPTION)
 - [ ] for all but trivial changes (e.g., typo fixes), documentation your change in [NEWS.md](https://github.com/cloudyr/aws.s3/blob/master/NEWS.md) with a parenthetical reference to the issue number being addressed
 - [ ] if changing documentation, edit files in `/R` not `/man` and run `devtools::document()` to update documentation
 - [x] add code or new test files to [`/tests`](https://github.com/cloudyr/aws.s3/tree/master/tests/testthat) for any new functionality or bug fix
 - [x] make sure `R CMD check` runs without error before submitting the PR

### CODE REVIEW

**Comment by rvolykh** [comment]
Probably I found what is wrong `aws.signature (>= 0.3.7)` when last version is 0.3.5 should I switch?
But after local change `R CMD check` still fails but now with another error
```
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  pdflatex is not available
Error in running tools::texi2pdf()
```

**Comment by rvolykh** [comment]
My bad, after installing pdflatex R CMD check finished successfully. So should I commit DESCRIPTION with aws.signature (>= 0.3.5) ?

**Comment by leeper** [comment]
Please do not change the version requirement for aws.signature. The current version (on Github) is >0.3.7 and this version will be on CRAN soon (likely as 0.4.0).

**Comment by rvolykh** [comment]
Thanks I will revert last commit than, just a moment

**Comment by leeper** [comment]
I've merged in your first commit. Thanks, again!

**Pull request closed without merging**
